name: Port PagerDuty Incident Action
description: GitHub action to create repositories templated with Cookiecutter with Port integration
author: port-labs
inputs:
  token:
    description: 'The Pager Duty Token to use to authenticate with the API with permissions to create incidents'
    required: true
  portClientId:
    description: 'The Port Client ID to use to authenticate with the API'
    required: true
  portClientSecret:
    description: 'The Port Client Secret to use to authenticate with the API'
    required: true
  blueprintIdentifier:
    description: 'The blueprint identifier to use to populate the Port relevant entity'
    required: false
    default: 'pagerdutyIncident'
  incidentTitle:
    description: 'The title of the incident to create'
    required: true
  extraDetails:
    description: 'Extra details about the incident to create'
    required: false
  service:
    description: 'The service id to correlate the incident to'
    required: true
  urgency:
    description: 'The urgency of the incident to create'
    required: false
    default: 'high'
  actorEmail:
    description: 'The email of the actor to create the incident with'
    required: true
  portRunId:
    description: 'Port run ID to came from triggering the action'
    required: true
runs:
  using: docker
  image: Dockerfile